### ISSUE TITLE
VM Simulator

### ISSUE THREAD

**Issue by DavidSouther** [nand2tetris/web-ide#18]
Implement the Stack Virtual Machine from chapters 7 and 8, and page like the VM emulator stand-alone app.

Basic:
- [ ] Segments: argument, local, static, constant, this, that, pointer, temp
- [ ] push, pop
- [ ] add, sub, neg; eq, gt, lt; and, or, not
- [ ] Vars: RAM, SP, LCL, ARG, THIS, THAT, TEMP, R0-15

Control:
- [ ] labels
- [ ] goto
- [ ] if-goto
- [ ] function (args)
- [ ] call
- [ ] return

Tests: 
- [ ] Recognize segments, RAM[i], sp, currentFunction, and line variables.
- [ ] vmstep

**Comment by Goblinlordx** [comment]
Hi~ I just wanted to put it out there that I have a VM implementation for this that I think could potentially be useful. It was pretty... minimal to say the least and it has been a few years since I did the implementation (prior to me using TS much).

Either way, you can find it here:
https://github.com/Goblinlordx/hvm/blob/master/packages/vm/

Really, the core is here:
https://github.com/Goblinlordx/hvm/blob/master/packages/vm/VM.js

**Comment by Goblinlordx** [comment]
Hmmm~ I will need to check the book references. It was intended to simulate all the hardware and run actual code with video output and inputs. The "video" output just copies the framebuffer data and renders to a 2d canvas context. There is also functionality for dumping memory and registers for introspection and/or live view of those when running. Though I never did get around to implementing a "real" usable UI for it.

**Comment by Goblinlordx** [comment]
Ah~ I understand (looking back at the book). Sorry~ My misunderstanding.
